### ISSUE TITLE
Closing

### ISSUE THREAD

**Issue by kachick** [kachick/striuct#242]
## Tasks

- ~[ ] Update nixpkgs to 24.05 => don't ~
- [x] Drop ruby-head support
- [x] Release last version
- [x] Add note in README.md
